#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import sys
import os
import fcntl
import errno
import atexit
import subprocess
import logging
import argparse
from xmlrpc.server import SimpleXMLRPCServer, SimpleXMLRPCRequestHandler
import pifacedigitalio
from pifacedigitalio import MAX_BOARDS
from pifacedigitalio.core import _get_pifacedigital


__version_info__ = (0, 1, 2)
__version__ = ".".join(map(str, __version_info__))


def _check_type(object_, type_):
    if not isinstance(object_, type_):
        raise TypeError("hardware_addr must be {}, not {}".format(
            type_.__name__, object_.__class__.__name__))


def _check_hardware_addr(hardware_addr):
    _check_type(hardware_addr, int)

    if hardware_addr not in range(MAX_BOARDS):
        raise TypeError(
            "hardware_addr must be in {lower_addr}..{higher_addr}".format(
                lower_addr=0,
                higher_addr=MAX_BOARDS - 1,
            )
        )


def _check_pin_num(pin_num):
    _check_type(pin_num, int)

    if pin_num not in range(8):
        raise TypeError("pin_num must be in 0..7")


def _check_pin_value(value):
    _check_type(value, int)

    if value not in (0, 1):
        raise TypeError("value must be 1 or 0")


def _check_port_value(value):
    _check_type(value, int)

    if value < 0 or value > 255:
        raise TypeError("value must be in 0..255")


def write_output_port(hardware_addr, value):
    _check_hardware_addr(hardware_addr)
    _check_port_value(value)

    port = _get_pifacedigital(hardware_addr).output_port
    port.value = value
    result = port.value

    logging.info("XML-RPC: write_output_port({}, {}) -> 0b{:08b}".format(
        hardware_addr, value, result))

    return result


def write_output_pin(hardware_addr, pin_num, value):
    _check_hardware_addr(hardware_addr)
    _check_pin_num(pin_num)
    _check_pin_value(value)

    pin = _get_pifacedigital(hardware_addr).output_pins[pin_num]
    pin.value = value
    result = pin.value

    logging.info("XML-RPC: write_output_pin({}, {}, {}) -> {}".format(
        hardware_addr, pin_num, value, result))

    return result


def read_output_port(hardware_addr):
    _check_hardware_addr(hardware_addr)

    result = _get_pifacedigital(hardware_addr).output_port.value

    logging.info("XML-RPC: read_output_port({}) -> 0b{:08b}".format(hardware_addr, result))

    return result


def read_output_pin(hardware_addr, pin_num):
    _check_hardware_addr(hardware_addr)
    _check_pin_num(pin_num)

    result = _get_pifacedigital(hardware_addr).output_pins[pin_num].value

    logging.info("XML-RPC: read_output_pin({}, {}) -> {}".format(hardware_addr, pin_num, result))

    return result


def read_input_port(hardware_addr):
    _check_hardware_addr(hardware_addr)

    result = _get_pifacedigital(hardware_addr).input_port.value

    logging.info("XML-RPC: read_input_port({}) -> 0b{:08b}".format(hardware_addr, result))

    return result


def read_input_pin(hardware_addr, pin_num):
    _check_hardware_addr(hardware_addr)
    _check_pin_num(pin_num)

    result = _get_pifacedigital(hardware_addr).input_pins[pin_num].value

    logging.info("XML-RPC: read_input_pin({}, {}) -> {}".format(hardware_addr, pin_num, result))

    return result


listners = []


def init_event_handler(exe_path):
    if listners:
        return

    dev_null_r = open("/dev/null", "r")
    dev_null_w = open("/dev/null", "w")

    def quote(s):
        c = "'" if "'" not in s or '"' in s else '"'
        escape = {"\0": "\\0", "\a": "\\a", "\b": "\\b", "\t": "\\t",
                  "\n": "\\n", "\v": "\\v", "\f": "\\f", "\r": "\\r",
                  "\\": "\\\\"}
        escape[c] = "\\{}".format(c)
        return "".join((c, "".join(escape.get(c, c) for c in s), c))

    def on_event(address, pin_num, direction, timestamp):
        logging.info("event: address={} pin_num={} direction={} timestamp={}".format(
            address, pin_num, direction, timestamp))

        if not os.access(exe_path, os.X_OK):
            logging.error("cannot execute: {}".format(exe_path))
            return

        args = map(str, (exe_path, address, pin_num, direction, timestamp))
        retcode = subprocess.call(args, stdin=dev_null_r, stdout=dev_null_w,
                                  stderr=dev_null_w, env={})

        if retcode != 0:
            logging.error("{} dies with {} code".format(quote(exe_path), retcode))

    def get_handler(address):
        def handler(event):
            on_event(address, event.pin_num, event.direction, event.timestamp)

        return handler

    for address in range(MAX_BOARDS):
        try:
            pfd = _get_pifacedigital(address)
        except pifacedigitalio.NoPiFaceDigitalError:
            continue

        listner = pifacedigitalio.InputEventListener(chip=pfd)
        handler = get_handler(address)

        for pin_num in range(8):
            listner.register(pin_num, pifacedigitalio.IODIR_BOTH, handler)

        logging.info("add event handlers: address={}".format(address))

        listners.append(listner)

    for listner in listners:
        listner.activate()


def xmlrpc_serve(host, port):
    class XMLRPCRequestHandler(SimpleXMLRPCRequestHandler):

        rpc_paths = ("/RPC2", )

        def log_message(self, format, *args):  # pylint: disable=W0622
            logging.info("HTTP server: %s - - [%s] %s", self.address_string(),
                         self.log_date_time_string(), format % args)

    server = SimpleXMLRPCServer((host, port), requestHandler=XMLRPCRequestHandler)

    server.register_introspection_functions()
    server.register_multicall_functions()

    server.register_function(write_output_port)
    server.register_function(write_output_pin)
    server.register_function(read_output_port)
    server.register_function(read_output_pin)
    server.register_function(read_input_port)
    server.register_function(read_input_pin)

    logging.info("start XML-RPC server: scheme=http host={} port={} paths={}".format(
        host, port, XMLRPCRequestHandler.rpc_paths))
    server.serve_forever()


def daemonize(pidfile, stdout, stderr):
    # do the UNIX double-fork magic, see Stevens' "Advanced
    # Programming in the UNIX Environment" for details (ISBN 0201563177)
    # http://www.erlenstar.demon.co.uk/unix/faq_2.html#SEC16
    try:
        pid = os.fork()
    except OSError as e:
        sys.stderr.write("fork #1 failed: {} (errno: {})\n".format(e.strerror, e.errno))
        sys.exit(1)

    if pid > 0:
        sys.exit(0)

    # decouple from parent environment
    os.chdir("/")
    os.setsid()
    os.umask(0)

    try:
        pid = os.fork()
    except OSError as e:
        sys.stderr.write("fork #2 failed: {} (errno: {})\n".format(e.strerror, e.errno))
        sys.exit(1)

    if pid > 0:
        sys.exit(0)

    # redirect standard file descriptors
    si = open("/dev/null", "rb")
    os.dup2(si.fileno(), sys.stdin.fileno())

    sys.stdout.flush()
    so = open(stdout, "a+b")
    os.dup2(so.fileno(), sys.stdout.fileno())

    sys.stderr.flush()
    se = open(stderr, "a+b", 0)
    os.dup2(se.fileno(), sys.stderr.fileno())

    if pidfile:
        atexit.register(lambda: os.remove(pidfile))
        open(pidfile, "w").write("{}\n".format(os.getpid()))


class AlreadyLocked(IOError):
    pass


class ReleaseError(IOError):
    pass


class UnixFileLock(object):

    def __init__(self, lock_file):
        super(UnixFileLock, self).__init__()

        self.lock_file = lock_file
        self.__fd = open(lock_file, "wb")

    def acquire(self, blocking=False):
        op = fcntl.LOCK_EX

        if not blocking:
            op |= fcntl.LOCK_NB

        try:
            fcntl.flock(self.__fd, op)
        except IOError as e:
            if e.errno != errno.EAGAIN:
                raise

            raise AlreadyLocked()

    def release(self):
        fcntl.flock(self.__fd, fcntl.LOCK_UN)

        if self.is_locked():
            raise ReleaseError()

    def is_locked(self):
        try:
            fcntl.flock(self.__fd, fcntl.LOCK_EX)
        except IOError as e:
            if e.errno != errno.EAGAIN:
                raise

            fcntl.flock(self.__fd, fcntl.LOCK_UN)

            return True

        else:
            return False

    def __enter__(self):
        self.acquire()
        return self

    def __exit__(self, exc_type, exc_value, exc_traceback):
        self.release()


def main(argv=sys.argv):
    prog = os.path.basename(argv[0])
    parser = argparse.ArgumentParser(
        prog=prog,
        description="PiFace Digital daemon v{}".format(__version__),
    )
    parser.add_argument(
        "-v", "--version",
        action="version",
        version="%(prog)s v{}".format(__version__),
    )
    parser.add_argument(
        "-E", "--on-event",
        default="/etc/pifacedigitald/event",
        type=str,
        metavar="FILE",
        help="file to execute when input port state changes (default: /etc/pifacedigitald/event)",
    )
    parser.add_argument(
        "-H", "--host",
        default="localhost",
        type=str,
        help="XML-RPC server host (default: localhost)",
    )
    parser.add_argument(
        "-p", "--port",
        default=8050,
        type=int,
        help="XML-RPC server port (default: 8050)",
    )
    parser.add_argument(
        "-f", "--foreground",
        action="store_true",
        help="do not detach from the terminal",
    )
    parser.add_argument(
        "-l", "--log-file",
        type=str,
        metavar="FILE",
        help="log file path (default: /var/log/pifacedigitald.log)",
    )
    parser.add_argument(
        "-P", "--pid-file",
        default="/var/run/pifacedigitald.pid",
        type=str,
        metavar="FILE",
        help=("pid file path (default: /var/run/pifacedigitald.pid, "
              "not available in foreground mode)"),
    )
    parser.add_argument(
        "-o", "--stdout",
        default="/dev/null",
        type=str,
        metavar="FILE",
        help="redirect stdout to file (not available in foreground mode)",
    )
    parser.add_argument(
        "-e", "--stderr",
        default="/dev/null",
        type=str,
        metavar="FILE",
        help="redirect stderr to file (not available in foreground mode)",
    )
    args = parser.parse_args(argv[1:])

    if not args.log_file and not args.foreground:
        args.log_file = "/var/log/pifacedigitald.log"

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(name)s %(levelname)s %(message)s",
        filename=args.log_file,
    )

    lock = UnixFileLock("/var/lock/pifacedigitald.lock")

    try:
        lock.acquire()
    except AlreadyLocked:
        print("{}: program already running".format(prog), file=sys.stderr)
        return 1

    if not args.foreground:
        daemonize(args.pid_file, args.stdout, args.stderr)

    pifacedigitalio.init()
    init_event_handler(args.on_event)

    xmlrpc_serve(args.host, args.port)


if __name__ == "__main__":
    sys.exit(main())
